### ISSUE TITLE
Router links inside of slider items

### ISSUE THREAD

**Issue by sGerli** [vdanyliv/ngx-tiny-slider#14]
When using a routerLink inside of a slider item it doesn't get mapped to some of the dynamically generated ones in an infinite slider.

```html
<ngx-tiny-slider class="slider" #ngxSlider [config]="tinySliderConfig">
        <ng-container class="items">
            <button class="no-styles" #slideList *ngFor="let card of cards" [routerLink]="card.route">
                <div [class]="'card-poster card-poster--' + cardType">
                    <div class="card-poster__title">
                        <h3>{{card.title}}</h3>
                    </div>
                    <div class="card-poster__background" [ngStyle]="{ 'background-image': 'url(' + card.img + ')'}">
                    </div>
                </div>
            </button>
        </ng-container>
    </ngx-tiny-slider>
```
I already fixed the ngFor issue with one of the responses of #13.

**Comment by vdanyliv** [comment]
@sGerli could yu provide some sandbox where I can play with this?

**Comment by sGerli** [comment]
Heres a small demo: https://stackblitz.com/edit/angular-tiny-slider
In there you can see that the card at the left and other dynamically generated ones don't have a routerlink binded to them.

**Comment by vdanyliv** [comment]
@sGerli I changed render little bit, and everything works: 
```<a [routerLink]="card.route">
<img [src]="card.img">
</a>```
