### ISSUE TITLE
Minor change required. Adding NgxTinySliderService to public api

### ISSUE THREAD

**Issue by glani** [vdanyliv/ngx-tiny-slider#22]
After upgrading to angular 9 it is impossible to use NgxTinySliderService in sublibraries. It has to be exported as a separate service in public_api.ts. Otherwise you could face the issue

> ERROR in ./node_modules/hom-prices-lib/__ivy_ngcc__/fesm5/hom-prices-lib.js 487:74-101
"export 'NgxTinySliderService' (imported as 'ɵngcc4') was not found in 'ngx-tiny-slider'

**Comment by vdanyliv** [comment]
Hi @glani, I can export it, but could you please provide an example of why you need it?
Because I used it only to initialize slider, and actually there are no helper methods that you can use

**Comment by glani** [comment]
I use it for dynamic recreating of tinyslider. When slides are dynamic. I checked the core implementation tiny lib provides the way to recreate from scratch. 

waiteForDom does not work for me. However using service works perfectly.

**Comment by vdanyliv** [comment]
@glani, thanks for the explanation. In such case, will provide an export of this service today later

**Comment by vdanyliv** [comment]
@glani check v1.0.1
