### ISSUE TITLE
Is there any way in ngx-tiny slider to make arrow key to the right and left to the data instead of bottom or top

### ISSUE THREAD

**Issue by mksmanjit** [vdanyliv/ngx-tiny-slider#27]
Is there any way in ngx-tiny slider to make arrow key to the  right and left to the data instead of bottom or top?

I see there is one property in the jquery tiny slider which is **center**, which is doing the work.

Is there any similar way or any way to do the same functionality in ngx-tiny-slider

**Comment by vdanyliv** [comment]
@mksmanjit ngx-tiny-slider just a wrapper component for tiny-slider, you can use any api that provides tiny-slider libarary

**Comment by mksmanjit** [comment]
Ok Thanks
