### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by giancafigueroa** [vdanyliv/ngx-tiny-slider#28]
ReferenceError: Element is not defined

**Comment by vdanyliv** [comment]
@gianfigueroa ?

**Comment by gfigueroaalmera** [comment]
When, I run my app in angular universal, I am getting this error.

ReferenceError: Element is not defined

Can you add the if for angular universal or this is problem of tiny-slider lib.

**Comment by vdanyliv** [comment]
@gfigueroaalmera  could you provide a sandbox where I can reproduce this issue?

**Comment by DimaKomoff** [comment]
There are a lot of bugs in Angular Universal.
when i run project i got these errors:
-window is not defined.
-Element is not defined

**Comment by vdanyliv** [comment]
@DimaKomoff, I can help only if you provide a sandbox
