### ISSUE TITLE
ERROR TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by SvenBudak** [vdanyliv/ngx-tiny-slider#29]
I have a problem in this package. Maybe it is a bug.
Open your Sandbox demo: https://codesandbox.io/s/ngx-tiny-slider-wait-for-dom-gvvqh
and leave just one image in `listOfImages` like this:

```
  public listOfImages: Array<string> = [
    "http://www.mattsorger.com/newsletterpics/gsw07_01.jpg"
  ];
```

then you will get this error in console:
```
ERROR TypeError: Cannot read property 'getBoundingClientRect' of undefined
```

Any idea how we can fix it, that the slider also work if only 1 image is available? :)

**Comment by vdanyliv** [comment]
@SvenBudak the message that you wrote is thrown by tiny-slider library if you want to use lazy image loading, try to load one instance of the library

**Comment by vdanyliv** [comment]
@SvenBudak found an issue in the official repo of tiny-slider

https://github.com/ganlanyuan/tiny-slider/issues/545
