### ISSUE TITLE
Slider not working when nested *ngFor is used

### ISSUE THREAD

**Issue by muzammilversiani** [vdanyliv/ngx-tiny-slider#31]
Hi there,

I am trying to add items dynamically using *ngFor loop. Basically I am dividing each item in 2 columns and under each column, I am adding 2 elements. I am trying to make it run but getting error "No slide found".

Here is the code: https://stackblitz.com/edit/angular-ivy-zcb1t4

Thank you

**Comment by LionelENSFELDER** [comment]
Same here doesn't work with *ngFor
`<ngx-tiny-slider [config]="tinySliderConfig">
    <ng-container class="items" *ngFor="let movie of trendingMovies">
		<div class="item">
			<app-card [poster]="this.apiService.api.posters + movie.poster_path" [movie]="movie"></app-card>
		</div>
	</ng-container>
</ngx-tiny-slider>`

**Comment by vdanyliv** [comment]
take a look at the example https://codesandbox.io/s/ngx-tiny-slider-wait-for-dom-gvvqh?file=/src/app/app.component.html
