### ISSUE TITLE
Example interface errors

### ISSUE THREAD

**Issue by BenRacicot** [vdanyliv/ngx-tiny-slider#33]
Hello, thank you for porting Tiny-Slider to Angular. This is enormously needed. :)

Regarding the title, my [Stackblitz](https://stackblitz.com/edit/angular-vert-slider-awbdps?file=src%2Fapp%2Fshared%2Ftiny-slider%2Ftiny-slider.component.ts) repro demonstrates that the `NgxTinySliderSettingsInterface` interface only includes one param. But the demo explicitly shows setting the config with many params and thus an error.

Could you help me get that Stackblitz going?

**Comment by vdanyliv** [comment]
@BenRacicot interface include next props:

```
export interface NgxTinySliderInstanceInterface {
  domReady: Subject<any>;
  sliderInstance: TinySliderInstance;
  slideItemsContainerRef: ElementRef;
}
```

what extra do you need?

**Comment by BenRacicot** [comment]
Hey @vdanyliv sorry I dont follow what you're saying.

> interface include next props:

Thank you for pointing me to `NgxTinySliderInstanceInterface` but it does not contain `arrowKeys:boolean`

On this Github main page and the NPM page it explains to use the interface incorrectly, or so it seems. 
`NgxTinySliderSettingsInterface` is potentially misrepresented there.

Where you able to take a look at the [Stackblitz](https://stackblitz.com/edit/angular-ngx-tiny-slider?file=src%2Fapp%2Fshared%2Ftiny-slider%2Ftiny-slider.component.ts) which is not working with ngx-tiny-slider?

```
  // tinySliderConfig: NgxTinySliderSettingsInterface; // Github/NPM instructions
  tinySliderConfig: NgxTinySliderInstanceInterface;

  ngOnInit() {
    this.tinySliderConfig = {
      arrowKeys: true, // doesnt seem to exist on the interface?
      autoWidth: true,
      gutter: 10,
      controlsText: ["<", ">"]
    };
  }
```

**Comment by vdanyliv** [comment]
@BenRacicot  NgxTinySliderSettingsInterface extends TinySliderSettings, clone my demo stackblitz, and enjoy. I will take a look at your stackblitz later (make sure that your stackblitz and angular project configured properly)
