### ISSUE TITLE
Duplicate identifier 'preventScrollOnTouch'. 

### ISSUE THREAD

**Issue by GeorgeHulpoi** [vdanyliv/ngx-tiny-slider#34]
Error: node_modules/tiny-slider/src/tiny-slider.d.ts:260:5 - error TS2300: Duplicate identifier 'preventScrollOnTouch'.

**Comment by vdanyliv** [comment]
@GeorgeHulpoi check this one https://github.com/vdanyliv/ngx-tiny-slider/issues/30
