### ISSUE TITLE
navAsThumbnails

### ISSUE THREAD

**Issue by shamseen** [vdanyliv/ngx-tiny-slider#8]
Hi! 

I'm a super newbie to Angular and can't seem to figure out how to get the slider thumbnails working. The initial guide on the readme works fine, but I don't know where I'm supposed to be adding my options?

I'm adding it to a separate component (if that matters):

```
|-- app
     |-- carousel
          |-- carousel.component.ts
     |-- app.component.ts
     |-- app.module.ts
```

**Comment by vdanyliv** [comment]
Hi @shamseen, I assume you want to apply some custom settings, so the easiest way to do this is to pass your options into the component. Could you please paste your slider config object here?

**Comment by shamseen** [comment]
Thanks! Just to make sure I was adding the options correctly, I tried changing the number of items and allowing mouse drag. Only the latter worked.

```Javascript
this.tinySliderConfig = {
	arrowKeys: true,
	autoWidth: true,
	gutter: 10,
	controlsText: ['<', '>'],
	items: 2,
	mouseDrag: true,
	navAsThumbnails: true
};
```

**Comment by vdanyliv** [comment]
@shamseen thanks for the reply, I will check your config today, and I will let you know if I found any issue

**Comment by vdanyliv** [comment]
@shamseen I made some investigation and have some answers to your questions. First of all, if you want to use the custom **container** you should pass **element reference** instead of the name of the selector.

The same reference you should get for **controlsContainer** and **navContainer** options.
Try to make some demo and I will try to help you

**Comment by shamseen** [comment]
> use the custom **container** you should pass **element reference** instead of the name of the selector.

@vdanyliv okay,  so i tried to add an element reference but i still get errors

i've made a [repository](https://github.com/shamseen/test-app/blob/master/src/app/app-shell/app-shell.component.ts) with [browser console errors](https://github.com/shamseen/test-app/blob/master/errorLogs/tiny-slider_elementRef)

**Comment by vdanyliv** [comment]
@shamseen I will run your test app later today, on the error screenshot, I see that element did not found.

**Comment by shamseen** [comment]
@vdanyliv where do I put that reference?

**Comment by vdanyliv** [comment]
@shamseen in your config

**Comment by shamseen** [comment]
@vdanyliv i'm sorry i still don't understand. can  you give me an example of what the reference would look like?

are you talking about the config options in the component? 

``` JavaScript
		this.tinySliderConfig = {
			arrowKeys: true,
			autoWidth: true,
			gutter: 10,
			controlsText: ['<', '>'],
			mouseDrag: true,
			container: carousel,
			items: 3,
			controlsContainer: "#customize-controls",
			navContainer: "#customize-thumbnails",
			navAsThumbnails: true,
			autoplay: true,
			autoplayTimeout: 1000,
			autoplayButton: "#customize-toggle",
			swipeAngle: false,
			speed: 400
		};
```

**Comment by vdanyliv** [comment]
@shamseen I will update examples in next release
