### ISSUE TITLE
Interact with tiny-slider after ngOnInit?

### ISSUE THREAD

**Issue by rgustavsson** [vdanyliv/ngx-tiny-slider#9]
Is it possible to interact with the slider, e.g. slider.play(), slider.pause() etc. after ngOnInit?

**Comment by vdanyliv** [comment]
Hi @rgustavsson, thanks for your question. After component initialization, I didn't provide such a possibility, but I can add this functionality in the next release

**Comment by vdanyliv** [comment]
@rgustavsson I investigate you question, actually, you can create a reference to the element **#slider** and use **ViewChild** in your component to get access to the slider instance.
<img width="538" alt="Screen Shot 2019-08-07 at 4 13 31 PM" src="https://user-images.githubusercontent.com/7668527/62625643-50fe7b80-b92e-11e9-8c1b-d98893259b90.png">
<img width="943" alt="Screen Shot 2019-08-07 at 4 14 04 PM" src="https://user-images.githubusercontent.com/7668527/62625688-696e9600-b92e-11e9-891d-6b91171abdbb.png">

**Comment by rgustavsson** [comment]
I haven't worked with ViewChild before but I'll have a look at that.
Thanks for the feedback @vdanyliv

**Comment by rgustavsson** [comment]
I got your example to work - thanks!

**Comment by dilantha111** [comment]
Hi @vdanyliv  this is also what is exactly I want. But I couldn't access sliderInstance. I tried it this way. 
@ViewChild('test', { read: ElementRef, static: false })
  private test: ElementRef;

and then this.test.nativeElement. Any help would be really appreciated.

**Comment by vdanyliv** [comment]
@dilantha111 
```
@ViewChild('test') test;

someMethod() {
console.log(this.test) => show return slider instance
}
```
